# Generated by Django 5.0.6 on 2024-09-24 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cart_id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("session_key", models.CharField(max_length=40, unique=True)),
            ],
            options={
                "db_table": "cart",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("cart_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveSmallIntegerField()),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="carts.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menus.product"
                    ),
                ),
            ],
            options={
                "db_table": "cart_item",
            },
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"), name="unique_cart_product"
            ),
        ),
    ]
