# Generated by Django 5.0.6 on 2024-09-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("session_key", models.CharField(max_length=40)),
                ("customer_name", models.CharField(max_length=70)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone_number", models.CharField(max_length=15)),
                ("table_number", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Awaiting Payment"),
                            (2, "Processing"),
                            (3, "Completed"),
                            (4, "Canceled"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("order_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.PositiveSmallIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="menus.product"
                    ),
                ),
            ],
            options={
                "db_table": "order_item",
            },
        ),
    ]
